from extensions import db

class PowerStations(db.Model):
  """Power Stations"""
  __tablename__='power_stations'
  id = db.Column(db.Integer, nullable=False, primary_key=True)
  licencearea = db.Column(db.Text)
  sitename = db.Column(db.Text)
  sitefunctionallocation = db.Column(db.Text, unique=True)
  sitetype = db.Column(db.Text)
  sitevoltage = db.Column(db.Integer)
  esqcroverallrisk = db.Column(db.Text)
  gridref = db.Column(db.Text, unique=True)
  siteassetcount = db.Column(db.Integer)
  electricalassetcount = db.Column(db.Integer)
  powertransformercount = db.Column(db.Integer)
  civilassetcount = db.Column(db.Integer)
  longitude = db.Column(db.Float)
  latitude = db.Column(db.Float)
  street = db.Column(db.Text)
  suburb = db.Column(db.Text)
  towncity = db.Column(db.Text)
  county = db.Column(db.Text)
  postcode = db.Column(db.Text)
  yearcommissioned = db.Column(db.Integer)
  datecommissioned = db.Column(db.Text)
  siteclassification = db.Column(db.Text)
  assessmentdate = db.Column(db.Date)
  last_report = db.Column(db.Text)
  calculatedresistance = db.Column(db.Text)
  measuredresistance_ohm = db.Column(db.Float)
  next_assessmentdate = db.Column(db.Date)
  local_authority = db.Column(db.Text)
  local_authority_code = db.Column(db.Text)